spring:
  application:
    name: '@project.name@'
  redis:
    host: 0.0.0.0
    port: 55000
    password: redispw
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 30
            class: org.quartz.simpl.SimpleThreadPool
          jobStore:
            misfireThreshold: 60000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            useProperties: true
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/uzum-scrapper
    username: postgres
    password: 5053
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
app:
  job:
    cron:
      delete-product-cache: 0 0/30 * * * ?
      position-product-job: 0 0 0,21 ? * * *
      product-job: 0 0 0,21 ? * * *
      position-job: 0 0 4 ? * * *
      category-job: 0 0 1 ? * * *
      trim-job: 0 0/60 * * * ?
      token-job: 0/10 * * * * ?
  aws-stream:
    endpoint: 'yds.serverless.yandexcloud.net'
    accessKey: fake-access-key
    secretKey: fake-secret-key
    region: ru-central-1
    uzum-stream:
      name: '/ru-central1/b1gtojcphtuae1n9siie/etnvck8jo3kuh0vilc57/uzum-stream'

  stream:
    product:
      key: uzum-product-stream
      group: uzum-product-group
      maxlen: 50000
      waitPending: 0
    position:
      key: uzum-position-stream
      group: uzum-position-group
      maxlen: 50000
      waitPending: 0
    category:
      key: uzum-category-stream
      group: uzum-category-group
      maxlen: 50000
      waitPending: 0
  integration:
    timeout:
      from: 3500
      to: 5000
    uzum:
      token:
    styx:

redis:
  local: false